version: '3.9'

volumes:
  mysql:

services:
  db:
    image: mysql:8.0
    container_name: airport_db
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./src/main/resources/db/init_db/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airport_db        # Definiraj bazu podataka za aerodrom
      MYSQL_USER: airport_user          # Definiraj korisnika za bazu podataka
      MYSQL_PASSWORD: airport_pass      # Definiraj lozinku za korisnika

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: airport_pma
    restart: always
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=airport_user           # Korisnik za pristup phpMyAdmin
      - PMA_PASSWORD=airport_pass       # Lozinka za pristup phpMyAdmin
